### ISSUE TITLE
GitHub Action shows PHP 7.4 runtime where 7.1, 7.2 or 7.3 is configured

### ISSUE THREAD

**Issue by ttomdewit** [beechit/json-to-code-climate-subset-converter#11]
Hi,

Within the "Run PHPUnit tests" GitHub Action we define the 7.1, 7.2, 7.3 and 7.4 PHP versions in the strategy matrix.

```yml
name: Run PHPUnit tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [7.1, 7.2, 7.3, 7.4]
        dependencies: [lowest, highest]
      
    steps:
    - uses: actions/checkout@v1

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run PHPUnit tests
      run: composer phpunit
```
Please see https://github.com/beechit/json-to-code-climate-subset-converter/actions/runs/32921220. Here it's clear that every build (lowest and highest for all PHP versions) are using PHPUnit 8.5.2 running on PHP 7.4.1 with Xdebug 2.9.0.
